-- Schema gerado automaticamente a partir do dicionario.csv

CREATE TABLE unidade_federativa (
  cod_uf NUMERIC(2) NOT NULL UNIQUE,
  sigla CHAR(2) NOT NULL UNIQUE,
  nome VARCHAR(22) NOT NULL UNIQUE,
  lat_uf REAL NOT NULL,
  long_uf REAL NOT NULL,
  regiao VARCHAR(12) NOT NULL,
  populacao INTEGER NOT NULL,
  PRIMARY KEY (cod_uf)
);

CREATE TABLE municipios (
  cod_mun NUMERIC(7) NOT NULL UNIQUE,
  nome_mun VARCHAR(30) NOT NULL,
  fuso VARCHAR(30) NOT NULL,
  lat_mun REAL NOT NULL,
  long_mun REAL NOT NULL,
  ddd NUMERIC(2) NOT NULL,
  cod_uf NUMERIC(2) NOT NULL,
  PRIMARY KEY (cod_mun),
  FOREIGN KEY (cod_uf) REFERENCES unidade_federativa(cod_uf) ON DELETE RESTRICT
);

CREATE TABLE ubs (
  cnes NUMERIC(7) NOT NULL UNIQUE,
  logradouro VARCHAR(80) NOT NULL,
  lat_ubs REAL NOT NULL,
  long_ubs REAL NOT NULL,
  cod_mun NUMERIC(7) NOT NULL,
  PRIMARY KEY (cnes),
  FOREIGN KEY (cod_mun) REFERENCES municipios(cod_mun) ON DELETE RESTRICT
);

CREATE TABLE escolaridade (
  id INTEGER NOT NULL UNIQUE,
  "desc" VARCHAR(50) NOT NULL UNIQUE,
  PRIMARY KEY (id)
);

CREATE TABLE raca (
  id INTEGER NOT NULL UNIQUE,
  "desc" VARCHAR(12) NOT NULL UNIQUE,
  PRIMARY KEY (id)
);

CREATE TABLE tipo_notificacao (
  id INTEGER NOT NULL UNIQUE,
  tipo VARCHAR(10) NOT NULL UNIQUE,
  PRIMARY KEY (id)
);

CREATE TABLE tipo_infectado (
  id INTEGER NOT NULL UNIQUE,
  "desc" VARCHAR(6) NOT NULL UNIQUE,
  PRIMARY KEY (id)
);

CREATE TABLE notificacao_de_infectados (
  id INTEGER NOT NULL UNIQUE,
  dt_notific DATE,
  ano_nasc NUMERIC(4) NOT NULL,
  dt_invest DATE NOT NULL,
  cs_sexo CHAR(1) NOT NULL,
  vomito BOOLEAN,
  cs_gestant NUMERIC(1) NOT NULL,
  sangram BOOLEAN,
  dt_sin_pri DATE,
  classi_fin NUMERIC(1) NOT NULL,
  criterio NUMERIC(1),
  tpautocto NUMERIC(1),
  resul_vi_n NUMERIC(1),
  doenca_tra NUMERIC(1),
  evolucao NUMERIC(1),
  dt_obito DATE,
  dt_encerra DATE,
  dt_digita DATE NOT NULL,
  nduplic_n NUMERIC(1),
  sorotipo NUMERIC(1),
  resul_soro NUMERIC(1),
  febre BOOLEAN,
  acido_pept BOOLEAN,
  alrm_abdom BOOLEAN,
  alrm_hemat BOOLEAN,
  alrm_hipot BOOLEAN,
  alrm_letar BOOLEAN,
  alrm_liq BOOLEAN,
  alrm_plaq BOOLEAN,
  alrm_sang BOOLEAN,
  alrm_vom BOOLEAN,
  artralgia BOOLEAN,
  artrite BOOLEAN,
  auto_imune BOOLEAN,
  cefaleia BOOLEAN,
  clinic_chik NUMERIC(1),
  complica NUMERIC(1),
  con_fhd NUMERIC(1),
  conjuntvit BOOLEAN,
  diabetes BOOLEAN,
  dor_costas BOOLEAN,
  dor_retro BOOLEAN,
  dt_alrm DATE,
  dt_chik_s1 DATE,
  dt_chik_s2 DATE,
  dt_grav DATE,
  dt_ns1 DATE,
  dt_pcr DATE,
  dt_prnt DATE,
  dt_soro DATE,
  dt_viral DATE,
  epistaxe NUMERIC(1),
  evidencia NUMERIC(1),
  exantema NUMERIC(1),
  gengivo NUMERIC(1),
  grav_ast BOOLEAN,
  grav_consc BOOLEAN,
  grav_conv BOOLEAN,
  grav_ench BOOLEAN,
  grav_extre BOOLEAN,
  grav_hemat BOOLEAN,
  grav_hipot BOOLEAN,
  grav_insuf BOOLEAN,
  grav_melen BOOLEAN,
  grav_metro BOOLEAN,
  grav_mioc BOOLEAN,
  grav_orgao BOOLEAN,
  grav_pulso BOOLEAN,
  grav_sang BOOLEAN,
  grav_taqui BOOLEAN,
  hematolog BOOLEAN,
  hematura BOOLEAN,
  hepatopat BOOLEAN,
  hipertensa BOOLEAN,
  histopa_n NUMERIC(1),
  imunoh_n NUMERIC(1),
  laco BOOLEAN,
  laco_n NUMERIC(1),
  leucopenia BOOLEAN,
  mani_hemor NUMERIC(1),
  metro NUMERIC(1),
  mialgia BOOLEAN,
  resul_prnt NUMERIC(1),
  nausea BOOLEAN,
  petequia_n BOOLEAN,
  petequias NUMERIC(1),
  plaq_menor NUMERIC(1),
  plasmatico NUMERIC(1),
  renal NUMERIC(1),
  res_chiks1 NUMERIC(1),
  res_chiks2 NUMERIC(1),
  resul_ns1 NUMERIC(1),
  resul_pcr_ NUMERIC(1),
  cod_mun_infec NUMERIC(7) NOT NULL,
  cod_mun_res NUMERIC(7) NOT NULL,
  ubs_not NUMERIC(7) NOT NULL,
  tipo_not INTEGER NOT NULL,
  tipo_infec INTEGER NOT NULL,
  raca INTEGER NOT NULL,
  escolaridade INTEGER NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (cod_mun_infec) REFERENCES municipios(cod_mun) ON DELETE RESTRICT,
  FOREIGN KEY (cod_mun_res) REFERENCES municipios(cod_mun) ON DELETE RESTRICT,
  FOREIGN KEY (ubs_not) REFERENCES ubs(cnes) ON DELETE CASCADE,
  FOREIGN KEY (tipo_not) REFERENCES tipo_infectado(id) ON DELETE RESTRICT,
  FOREIGN KEY (tipo_infec) REFERENCES tipo_notificacao(id) ON DELETE RESTRICT,
  FOREIGN KEY (raca) REFERENCES raca(id) ON DELETE RESTRICT,
  FOREIGN KEY (escolaridade) REFERENCES escolaridade(id) ON DELETE RESTRICT,
  CHECK (     (
        cs_sexo = 'F' AND
        (EXTRACT(YEAR FROM CURRENT_DATE) - ano_nasc) <= 10
        AND cs_gestant = '6'
    )
    OR
    (
        cs_sexo = 'M' AND cs_gestant = '6'
    )
    OR
  (
        cs_sexo = 'F' AND
        (EXTRACT(YEAR FROM CURRENT_DATE) - ano_nasc) > 10
        AND cs_gestant IN ('1', '2', '3', '4', '5', '9')
    )),
  CHECK ((tipo_infec = 1 AND sangram IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND resul_vi_n IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND sorotipo IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND resul_soro IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND febre IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND acido_pept IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND alrm_abdom IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND alrm_hemat IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND alrm_hipot IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND alrm_letar IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND alrm_liq IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND alrm_plaq IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND alrm_sang IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND alrm_vom IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND artralgia IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND artrite IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND auto_imune IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND cefaleia IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND clinic_chik IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND complica IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND con_fhd IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND conjuntvit IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND diabetes IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND dor_costas IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND dor_retro IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND dt_alrm IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND dt_chik_s1 IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND dt_chik_s2 IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND dt_grav IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND dt_ns1 IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND dt_pcr IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND dt_prnt IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND dt_soro IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND dt_viral IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND epistaxe IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND evidencia IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND exantema IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND gengivo IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND grav_ast IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND grav_consc IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND grav_conv IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND grav_ench IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND grav_extre IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND grav_hemat IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND grav_hipot IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND grav_insuf IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND grav_melen IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND grav_metro IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND grav_mioc IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND grav_orgao IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND grav_pulso IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND grav_sang IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND grav_taqui IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND hematolog IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND hematura IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND hepatopat IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND hipertensa IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND histopa_n IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND imunoh_n IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND laco IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND laco_n IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND leucopenia IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND mani_hemor IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND metro IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND mialgia IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND resul_prnt IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND nausea IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND petequia_n IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND petequias IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND plaq_menor IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND plasmatico IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND renal IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND res_chiks1 IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND res_chiks2 IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND resul_ns1 IS NULL) OR (tipo_infec <> 1)),
  CHECK ((tipo_infec = 1 AND resul_pcr_ IS NULL) OR (tipo_infec <> 1))
);

